added a service for loading contacts
creamscript/android-65apps-2021 pull request #3
Opened 2021-03-27 14:58 UTC by creamscript

Выделен привязанный сервис для загрузки списка контактов,
согласно заданию:

Необходимо написать привязанный сервис, который будет иметь публичное API предоставляющее список контактов.
Список контактов пока захардкодить.

Сервис должен предоставлять список контактов на другом потоке программы - т.е. должен создавать поток для загрузки списка контактов

Сценарий использования:
- Главная активность привязывается к сервису с помощью bindService
- Получает публичный интерфейс сервиса
- Предоставляет публичный интерфейс сервиса фрагментам
- Фрагменты используют публичный интерфейс сервиса для получения данных контактов

Публичный интерфейс должен иметь 2 метода:
1. Метод получения списка контактов с короткой информацией (Будет использоваться в фрагменте списка контактов) - метод должен быть асинхронным
2. Метод получения детальной информации по ID контакта(Будет использоваться в фрагменте деталей контакта) - метод должен быть асинхронным

2021-03-28 18:38 UTC, KalimullinIlnaz requested changes

2021-03-28 18:38 UTC, KalimullinIlnaz commented on app/src/main/java/com/creamscript/bulychev/ContactDetailsFragment.kt
>          (activity as AppCompatActivity?)
Не приводи к нуллабельному типу, ты же тут точно знаешь, что активити расширяет этот класс, смысла от лишних проверок на нулл нет

2021-03-28 18:38 UTC, KalimullinIlnaz commented on app/src/main/java/com/creamscript/bulychev/ContactDetailsFragment.kt
> +    private var serviceDeliverable: ContactService.IService? = null
нужно обнулить

2021-03-28 18:38 UTC, KalimullinIlnaz commented on app/src/main/java/com/creamscript/bulychev/ContactDetailsFragment.kt
> +            view?.post(Runnable {
requireView() везде

2021-03-28 18:38 UTC, KalimullinIlnaz commented on app/src/main/java/com/creamscript/bulychev/ContactDetailsFragment.kt
> +                var contactName: TextView? = view?.findViewById<TextView>(R.id.contactDetailsName)
вместо var используй val

2021-03-28 18:38 UTC, KalimullinIlnaz commented on app/src/main/java/com/creamscript/bulychev/ContactDetailsFragment.kt
> +                contactPhoto?.setImageDrawable(
`  contactPhoto?.setImageDrawable(ContextCompat.getDrawable(requireContext(), contact.photoResId))`

2021-03-28 18:38 UTC, KalimullinIlnaz commented on app/src/main/java/com/creamscript/bulychev/ContactDetailsFragment.kt
> +            view?.post(Runnable {
здесь студия подсказывает, что можно избавиться от runnable, пользуйся этим

2021-03-28 18:38 UTC, KalimullinIlnaz commented on app/src/main/java/com/creamscript/bulychev/ContactDetailsFragment.kt
> +                var contactName: TextView? = view?.findViewById<TextView>(R.id.contactDetailsName)
здесь также студия подсказывает, не игнорируй

2021-03-28 18:38 UTC, KalimullinIlnaz commented on app/src/main/java/com/creamscript/bulychev/ContactDetailsFragment.kt
> +                contactDescription?.text = contact.contactDescription
здесь можно избавится от того, чтобы делать каждый элемент вью нуллабельным, просто перед сеттингом данных, проверить какую либо из вью на то что она не нулл и делай сеттинг

2021-03-28 18:38 UTC, KalimullinIlnaz commented on app/src/main/java/com/creamscript/bulychev/ContactDetailsFragment.kt
> +    private val TAG_LOG = "DETAILS"
перенеси в компаньён объект, раз он у тебя здесь есть и сделай константой уровня компиляции

2021-03-28 18:38 UTC, KalimullinIlnaz commented on app/src/main/java/com/creamscript/bulychev/ContactEntity.kt
> +    , @DrawableRes val photoResId: Int
запятая на той же строке, что и переменная

2021-03-28 18:38 UTC, KalimullinIlnaz commented on app/src/main/java/com/creamscript/bulychev/ContactListDeliverable.kt
> +    fun getContactList(array: ArrayList<ContactEntity>)
здесь можно расширить границы типа и использовать просто list

2021-03-28 18:38 UTC, KalimullinIlnaz commented on app/src/main/java/com/creamscript/bulychev/ContactListFragment.kt
> +            view?.post(Runnable {
замечания аналогичны

2021-03-28 18:38 UTC, KalimullinIlnaz commented on app/src/main/java/com/creamscript/bulychev/ContactService.kt
> +    private val TAG_LOG = "SERVICE"
сделай константой на уровне файла

2021-03-28 18:38 UTC, KalimullinIlnaz commented on app/src/main/java/com/creamscript/bulychev/ContactEntity.kt
> +    , @DrawableRes val photoResId: Int
аналогично в файле mock data

2021-03-28 18:38 UTC, KalimullinIlnaz commented on app/src/main/java/com/creamscript/bulychev/MainActivity.kt
> +            if(isCreateMainFragment)
нужны {}

2021-03-28 18:38 UTC, KalimullinIlnaz commented on app/src/main/java/com/creamscript/bulychev/MainActivity.kt
> +    private val TAG_LOG = "MAIN"
также сделай константой

2021-03-28 18:38 UTC, KalimullinIlnaz commented on app/src/main/java/com/creamscript/bulychev/MainActivity.kt
> +    override fun getService() : ContactService? {
можно написать более функционально
  override fun getService()  = contactService

2021-03-28 18:54 UTC, creamscript commented on app/src/main/java/com/creamscript/bulychev/ContactEntity.kt
> +    , @DrawableRes val photoResId: Int
есть код-стайлы какие-то? почему? при работе с SQL практикую такое, типа что бы можно было закомментировать. Пока писал предыдущее предложение, вспомнил, что слышал что можно вроде запятую оставлять у последнего поля в Kotlin :) и от такого написание как у меня смысла нет

2021-03-28 19:00 UTC, creamscript commented on app/src/main/java/com/creamscript/bulychev/MainActivity.kt
> +            if(isCreateMainFragment)
прости, не понял, где?

2021-03-28 19:30 UTC, KalimullinIlnaz commented on app/src/main/java/com/creamscript/bulychev/ContactEntity.kt
> +    , @DrawableRes val photoResId: Int
https://kotlinlang.org/docs/coding-conventions.html

2021-03-28 19:31 UTC, KalimullinIlnaz commented on app/src/main/java/com/creamscript/bulychev/MainActivity.kt
> +            if(isCreateMainFragment)
у блока кода, который выполняется если isCreateMainFragment = true

2021-03-28 19:36 UTC, creamscript commented on app/src/main/java/com/creamscript/bulychev/MainActivity.kt
> +            if(isCreateMainFragment)
так? `if(isCreateMainFragment) { openContactList(R.id.fragment_container, ContactListFragment()) }` Не обязательно вроде, если одна строка в блоке? или что-то не понял?

2021-04-01 16:26 UTC, KalimullinIlnaz commented on app/src/main/java/com/creamscript/bulychev/ContactDetailsFragment.kt
> +                contactPhoto.setImageDrawable(ContextCompat.getDrawable(requireContext(), contact.photoResId))
на момент выполнения этого callback-а вьюшек уже может не быть, нужно проверить на нулл их перед установкой данных

2021-04-01 16:26 UTC, KalimullinIlnaz commented on app/src/main/java/com/creamscript/bulychev/ContactDetailsFragment.kt
> +    private var serviceDeliverable: ContactService.IService? = null
не исправлено
что я имелл ввиду
в методе обратном тому, в котором ты устанавливал значение этой переменной нужно написать serviceDeliverable = null

2021-04-01 16:29 UTC, KalimullinIlnaz requested changes

2021-04-01 16:29 UTC, KalimullinIlnaz commented on app/src/main/java/com/creamscript/bulychev/ContactListDeliverable.kt
> +    fun getContactList(list: List<T>)
зачем ты сделал дженерики, я же вроде понятно написал, что нужно использовать list вместо array
если что то непонятно пиши, я отвечу всегда

2021-04-01 16:29 UTC, KalimullinIlnaz commented on app/src/main/java/com/creamscript/bulychev/ContactListFragment.kt
> +    private lateinit var serviceDeliverable: ContactService.IService
аналогично нужно обнулить эту переменную в onDetach

2021-04-01 17:19 UTC, KalimullinIlnaz approved these changes

2021-04-01 17:19 UTC, merged