Birthday reminder created
creamscript/android-65apps-2021 pull request #5
Opened 2021-04-18 07:00 UTC by creamscript

1. Добавлено к деталям контакта поле "День рождения"
2. Добавлен переключатель о вкл. и выкл. напоминания "Дне рождении", состояние зависит
3. 

|Details |Notify|
|--------|-------|
|![Screenshot_1618727987](https://user-images.githubusercontent.com/8039856/115136972-5a614600-a034-11eb-8dda-815b6624416a.png)|![Screenshot_1618728012](https://user-images.githubusercontent.com/8039856/115136982-63521780-a034-11eb-94f2-46a7566c11b9.png)|

2021-04-18 10:40 UTC, KalimullinIlnaz requested changes

2021-04-18 10:40 UTC, KalimullinIlnaz commented on app/src/main/java/com/creamscript/bulychev/activities/MainActivity.kt
>              }
выдели под эту логику отдельный метод с понятным названием

2021-04-18 10:40 UTC, KalimullinIlnaz commented on app/src/main/java/com/creamscript/bulychev/activities/MainActivity.kt
> +            if (contactDetailsFragment == "contactDetailsLayout") {
contactDetailsLayout в константы

2021-04-18 10:40 UTC, KalimullinIlnaz commented on app/src/main/java/com/creamscript/bulychev/data/Contact.kt
> +class Contact(
data class

2021-04-18 10:40 UTC, KalimullinIlnaz commented on app/src/main/java/com/creamscript/bulychev/data/Contact.kt
> +        private var notifyBirthday: Boolean
все переменные val

2021-04-18 10:40 UTC, KalimullinIlnaz commented on app/src/main/java/com/creamscript/bulychev/data/Contact.kt
> +    fun getNotifyBirthday(): Boolean { return notifyBirthday }
эти методы будут не нужны
в data class-ах они генерируются автоматически

2021-04-18 10:40 UTC, KalimullinIlnaz commented on app/src/main/java/com/creamscript/bulychev/fragments/ContactDetailsFragment.kt
> +    private var switchAlarm: Switch? = null
нужно обнулить эту вьюшку в onDestroyView, иначе будут утечки памяти

2021-04-18 10:40 UTC, KalimullinIlnaz commented on app/src/main/java/com/creamscript/bulychev/data/Contact.kt
> +    fun stopNotify(context: Context?) {
передавай сюда nonnull context, не зачем лишние проверки на null создать внутри кода

2021-04-18 10:40 UTC, KalimullinIlnaz commented on app/src/main/java/com/creamscript/bulychev/data/Contact.kt
> +    fun scheduleNotify(context: Context?, calendar: Calendar) {
аналогично и здесь

2021-04-18 10:40 UTC, KalimullinIlnaz commented on app/src/main/java/com/creamscript/bulychev/fragments/ContactDetailsFragment.kt
> +                 contactDetails.scheduleNotify(context, calendar)
requireContext() вместо context

2021-04-18 10:40 UTC, KalimullinIlnaz commented on app/src/main/java/com/creamscript/bulychev/fragments/ContactDetailsFragment.kt
> +                 contactDetails.stopNotify(context)
requireContext()

2021-04-18 10:40 UTC, KalimullinIlnaz commented on app/src/main/java/com/creamscript/bulychev/receivers/NotifyBroadcastReceiver.kt
> +        val alarmManager = context?.getSystemService(Context.ALARM_SERVICE) as? AlarmManager
здесь студия говорит, что можно не делать null првоерку, так как в метод приходит не null context

2021-04-18 10:40 UTC, KalimullinIlnaz commented on app/src/main/java/com/creamscript/bulychev/receivers/NotifyBroadcastReceiver.kt
> +        calendar.add(Calendar.YEAR, 1)
а если у человека день рождение 29-го февраля?
нужно этот кейс обработать

2021-04-18 10:40 UTC, KalimullinIlnaz commented on app/src/main/java/com/creamscript/bulychev/receivers/NotifyBroadcastReceiver.kt
> +    private var notificationManager: NotificationManager? = null
можно сделать локальной переменной в методе onReceive и не нуллбальной

2021-04-18 10:40 UTC, KalimullinIlnaz commented on app/src/main/java/com/creamscript/bulychev/data/Contact.kt
> +        this.notifyBirthday = true
а зачем нужна эта переменная?
видел проверки в деталях на коллбэке свитчера, почему мы не можем просто включать или отключать у контакта уведомление о др?

2021-04-18 12:56 UTC, creamscript commented on app/src/main/java/com/creamscript/bulychev/activities/MainActivity.kt
>              }
полностью этот кусок?
`val contactDetailsFragment = intent.getStringExtra(FRAGMENT_ID)
            val contactId = intent.getIntExtra(CONTACT_ID, 0)

            if (contactDetailsFragment == "contactDetailsLayout") {
                openContactDetails(R.id.fragment_container, ContactDetailsFragment.newInstance(contactId.toString()))
            } else {
                if(isCreateMainFragment) {
                    openContactList(R.id.fragment_container, ContactListFragment())
                }
            }`

2021-04-18 13:05 UTC, creamscript commented on app/src/main/java/com/creamscript/bulychev/activities/MainActivity.kt
> +            if (contactDetailsFragment == "contactDetailsLayout") {
+ // согласен, хотел же, тупанул, спасибо.

2021-04-18 13:15 UTC, creamscript commented on app/src/main/java/com/creamscript/bulychev/fragments/ContactDetailsFragment.kt
> +    private var switchAlarm: Switch? = null
`    override fun onDestroyView() {
        switchAlarm = null
        super.onDestroyView()
    }`

?

2021-04-18 13:23 UTC, creamscript commented on app/src/main/java/com/creamscript/bulychev/data/Contact.kt
> +class Contact(
// ok +

2021-04-18 13:23 UTC, creamscript commented on app/src/main/java/com/creamscript/bulychev/data/Contact.kt
> +        private var notifyBirthday: Boolean
// ok +

2021-04-18 13:41 UTC, creamscript commented on app/src/main/java/com/creamscript/bulychev/data/Contact.kt
> +    fun getNotifyBirthday(): Boolean { return notifyBirthday }
написал ключевое data class, если убираешь то ругается что методов нет, что-то не очень понял как это будет выглядеть.

2021-04-18 13:49 UTC, creamscript commented on app/src/main/java/com/creamscript/bulychev/data/Contact.kt
> +    fun stopNotify(context: Context?) {
// из-за того что context передавал при вызове вместо requireContext(), требовало. спасибо. +

2021-04-18 13:50 UTC, creamscript commented on app/src/main/java/com/creamscript/bulychev/data/Contact.kt
> +    fun scheduleNotify(context: Context?, calendar: Calendar) {
// из-за того что context передавал при вызове вместо requireContext(), требовало. спасибо. +

2021-04-18 13:50 UTC, creamscript commented on app/src/main/java/com/creamscript/bulychev/fragments/ContactDetailsFragment.kt
> +                 contactDetails.scheduleNotify(context, calendar)
// +

2021-04-18 13:50 UTC, creamscript commented on app/src/main/java/com/creamscript/bulychev/fragments/ContactDetailsFragment.kt
> +                 contactDetails.stopNotify(context)
// +

2021-04-18 13:51 UTC, creamscript commented on app/src/main/java/com/creamscript/bulychev/receivers/NotifyBroadcastReceiver.kt
> +        val alarmManager = context?.getSystemService(Context.ALARM_SERVICE) as? AlarmManager
// из-за того что context передавал при вызове вместо requireContext(), требовало. спасибо. +

2021-04-18 14:14 UTC, creamscript commented on app/src/main/java/com/creamscript/bulychev/receivers/NotifyBroadcastReceiver.kt
> +    private var notificationManager: NotificationManager? = null
// +

2021-04-18 14:46 UTC, creamscript commented on app/src/main/java/com/creamscript/bulychev/data/Contact.kt
> +        this.notifyBirthday = true
В деталях коллбэка мы загружаем данные и инициализируем элементы интерфейса. Проверка в onCheckedChanged нужна чтобы, когда мы открываем по нажатию на уведомление в тот же день и переходит в детали не ставилась тут же повторная задача на этот же день, чтобы не зациклится. В эту переменную мы сохраняем состояние, какое у нас у этого абонента по уведомлению, ну и пригодится для сохранение в БД, чтобы можно восстановить состояние. Так тут set-р наверное можно ещё сделать для установки состояния.

не так сделал?

2021-04-18 15:00 UTC, creamscript commented
@KalimullinIlnaz прошу ответить на уточняющие вопросы и ответы на вопросы. Смотри, я отвечаю на вопросы, задаю в ответ, как в этом случае обычно поступают: просто ждут ответа, дополнительно вызывают через @ или есть практика, что до исправления отправляют Re-request. Как это делается обычно? Хоть так, хоть так или как чаще всего принято? :)

2021-04-18 16:26 UTC, KalimullinIlnaz commented on app/src/main/java/com/creamscript/bulychev/activities/MainActivity.kt
>              }
ага

2021-04-18 16:27 UTC, KalimullinIlnaz commented on app/src/main/java/com/creamscript/bulychev/data/Contact.kt
> +    fun getNotifyBirthday(): Boolean { return notifyBirthday }
data class(val id: String)

2021-04-18 16:27 UTC, KalimullinIlnaz commented on app/src/main/java/com/creamscript/bulychev/fragments/ContactDetailsFragment.kt
> +    private var switchAlarm: Switch? = null
да

2021-04-18 16:46 UTC, creamscript commented on app/src/main/java/com/creamscript/bulychev/data/Contact.kt
> +    fun getNotifyBirthday(): Boolean { return notifyBirthday }
так ну это понятно.

к примеру делаю так
`data class Contact(
        val contactName: String,
        val firstPhone: String,
        val secondPhone: String,
        val firstEmail: String,
        val secondEmail: String,
        val contactDescription: String,
        @DrawableRes val photoResId: Int,
        val dateBirthday: Calendar,
        private var notifyBirthday: Boolean
)
{
//    fun getContactName(): String { return contactName }
//    fun getFirstPhone(): String { return firstPhone }
//    fun getSecondPhone(): String { return secondPhone }
//    fun getFirstEmail(): String { return firstEmail }
//    fun getSecondEmail(): String { return secondEmail }
//    fun getContactDescription(): String { return contactDescription }
//    fun getPhotoResId(): Int { return photoResId }
//    fun getDateBirthday(): Calendar { return dateBirthday }
//    fun getNotifyBirthday(): Boolean { return notifyBirthday }`

но вызовы к пример getContactName() становятся недоступны, или как-то по другому будет именоваться? не понимаю

2021-04-18 16:54 UTC, KalimullinIlnaz requested changes

2021-04-18 16:54 UTC, KalimullinIlnaz commented on app/src/main/java/com/creamscript/bulychev/data/Contact.kt
> +        this.notifyBirthday = true
не так должно быть
уведомление должно ставится только по нажатию на кнопку
когда ты открываешь детали контакта ты должен проверить есть ли задача в аларм менеджере и установить состояние кнопки по ней

2021-04-18 16:56 UTC, KalimullinIlnaz commented on app/src/main/java/com/creamscript/bulychev/data/Contact.kt
> +    fun getNotifyBirthday(): Boolean { return notifyBirthday }
просто вызываешь по названию поля, там внутри уже дернется сгенерированный метод get
почитай документацию котлина, там все подробно описано

2021-04-18 16:57 UTC, KalimullinIlnaz commented
можешь задавать вопросы, мне на почту приходят уведомления, что ты что то написал в комменты

2021-04-19 05:08 UTC, creamscript commented on app/src/main/java/com/creamscript/bulychev/data/Contact.kt
> +    fun getNotifyBirthday(): Boolean { return notifyBirthday }
// +

2021-04-19 05:08 UTC, creamscript commented on app/src/main/java/com/creamscript/bulychev/fragments/ContactDetailsFragment.kt
> +    private var switchAlarm: Switch? = null
// +

2021-04-19 05:16 UTC, creamscript commented on app/src/main/java/com/creamscript/bulychev/activities/MainActivity.kt
>              }
// +

2021-04-20 12:55 UTC, creamscript commented on app/src/main/java/com/creamscript/bulychev/receivers/NotifyBroadcastReceiver.kt
> +        calendar.add(Calendar.YEAR, 1)
// +

2021-04-20 12:55 UTC, creamscript commented on app/src/main/java/com/creamscript/bulychev/data/Contact.kt
> +        this.notifyBirthday = true
// +

2021-04-20 17:24 UTC, KalimullinIlnaz requested changes

2021-04-20 17:24 UTC, KalimullinIlnaz commented on app/src/main/java/com/creamscript/bulychev/activities/MainActivity.kt
> +    private fun selectFrag() {
navigateToFragmentByIntent

2021-04-20 17:32 UTC, creamscript commented on app/src/main/java/com/creamscript/bulychev/activities/MainActivity.kt
> +    private fun selectFrag() {
хорошо название :)

2021-04-20 17:52 UTC, KalimullinIlnaz approved these changes

2021-04-20 17:52 UTC, merged

2021-04-20 17:54 UTC, creamscript commented
@KalimullinIlnaz спасибо за проверку ДЗ-4!