Refactoring to MVVM
creamscript/android-65apps-2021 pull request #7
Opened 2021-05-14 10:12 UTC by creamscript

Произвести рефакторинг существующего кода приложения с использованием MVVM. Использованы компоненты от Google: ViewModel + LiveData. Вся работа из Сервиса перенесена в Репозитории. Сервис удален.

2021-05-14 17:32 UTC, KalimullinIlnaz requested changes

2021-05-14 17:32 UTC, KalimullinIlnaz commented on app/src/main/java/com/creamscript/bulychev/views/ContactDetailsFragment.kt
> +    }
сделай это сразу на месте
то есть там где подписываешься на лайв дату

2021-05-14 17:32 UTC, KalimullinIlnaz commented on app/src/main/java/com/creamscript/bulychev/ContactRepository.kt
> +    private var contact = MutableLiveData<Contact>()
переменные должны быть val
также live data не должно быть в репозитории, репозиторий занимается лишь тем, что отдает данные
то есть live data уходит во viewmodel

2021-05-14 17:32 UTC, KalimullinIlnaz commented on app/src/main/java/com/creamscript/bulychev/views/ContactListFragment.kt
> +
аналогично здесь можно перенести в место подписки или в отдельный метод, а в самой подписке просто сделать ссылку на метод

2021-05-14 17:32 UTC, KalimullinIlnaz commented on app/src/main/java/com/creamscript/bulychev/Constants.kt
> +const val CONTACT_DETAILS_LAYOUT_ID = "contactDetailsLayout"
не понял зачем нужна эта константа

2021-05-14 17:32 UTC, KalimullinIlnaz commented on app/src/main/java/com/creamscript/bulychev/viewmodels/ContactViewModel.kt
> +class ContactViewModel : ViewModel() {
Для каждого экрана должна быть своя viewModel

2021-05-14 18:18 UTC, creamscript commented on app/src/main/java/com/creamscript/bulychev/Constants.kt
> +const val CONTACT_DETAILS_LAYOUT_ID = "contactDetailsLayout"
CONTACT_DETAILS_LAYOUT_ID? это ID фрагмента в MainActivity сравниваю с ней. Ф-я navigateToFragmentByIntent()

2021-05-14 18:18 UTC, creamscript commented on app/src/main/java/com/creamscript/bulychev/Constants.kt
> +const val CONTACT_DETAILS_LAYOUT_ID = "contactDetailsLayout"
```
if (contactDetailsFragment == CONTACT_DETAILS_LAYOUT_ID) {
            openContactDetails(R.id.fragment_container, ContactDetailsFragment.newInstance(contactId.toString()))
```

2021-05-14 18:27 UTC, KalimullinIlnaz requested changes

2021-05-14 18:27 UTC, KalimullinIlnaz commented on app/src/main/java/com/creamscript/bulychev/views/MainActivity.kt
> +        val contactDetailsFragment = intent.getStringExtra(FRAGMENT_ID)
переименовать переменную совсем непонятно, вроде стринг из интента берешь, а переменная говорит, будто в ней класс фрагмент лежит

2021-05-14 18:28 UTC, KalimullinIlnaz commented on app/src/main/java/com/creamscript/bulychev/Constants.kt
> +const val CONTACT_DETAILS_LAYOUT_ID = "contactDetailsLayout"
а ну понятно, в NotifyBroadcastReceiver тогда замени хардкод на эту константу, я ее не нашел сразу и ничего не понял)

2021-05-15 06:36 UTC, creamscript commented on app/src/main/java/com/creamscript/bulychev/views/ContactListFragment.kt
> +
мне нужно в 2х местах использовать этот код, получается лучше в метод из предложенных вариантов. В чём преимущество метода перед неизменяемой переменной в данном случае?

2021-05-15 06:56 UTC, creamscript commented on app/src/main/java/com/creamscript/bulychev/views/ContactListFragment.kt
> +
вопрос снимаю, поспешил

2021-05-15 13:41 UTC, KalimullinIlnaz requested changes

2021-05-15 13:41 UTC, KalimullinIlnaz commented on app/src/main/java/com/creamscript/bulychev/viewmodels/ContactViewModel.kt
> +class ContactViewModel : ViewModel() {
раз эта вью модель для экрана деталей, то так и нужно назвать

2021-05-15 13:41 UTC, KalimullinIlnaz commented on app/src/main/java/com/creamscript/bulychev/views/ContactDetailsFragment.kt
> +                        ?.observe(viewLifecycleOwner, { postContactToDetails(it) })
.observe(viewLifecycleOwner, ::postContactToDetails)

2021-05-15 13:41 UTC, KalimullinIlnaz commented on app/src/main/java/com/creamscript/bulychev/viewmodels/ContactListViewModel.kt
> +        return contactList
нет смысла тут возвращать значение, оно все равно пустое, в этом методе получается нужно просто запустить поток, который получает данные и изменить в лайвдате значение, что и сделано и когда оно изменится подписчики уже все получат
аналогично в другой вьюмодели

2021-05-15 14:15 UTC, creamscript commented on app/src/main/java/com/creamscript/bulychev/viewmodels/ContactListViewModel.kt
> +        return contactList
действительно феил.

2021-05-15 16:20 UTC, creamscript commented on app/src/main/java/com/creamscript/bulychev/views/ContactDetailsFragment.kt
> +                        ?.observe(viewLifecycleOwner, { postContactToDetails(it) })
так, ссылкой на метод, не работает

2021-05-15 17:14 UTC, KalimullinIlnaz approved these changes

2021-05-15 17:14 UTC, merged

2021-05-15 17:36 UTC, creamscript commented
@KalimullinIlnaz спасибо за проверку PR!